orientation: clockwise
rows: 2
columns: 3
knobs: 1
layers:
  - buttons:
      - - a
        - ctrl-shift-d
      - - x
        - mclick
      - - calculator
        - x
    knobs:
      - ccw: wheelup
        press: volumeup
        cw: wheeldown
