orientation: clockwise
rows: 2
columns: 3
knobs: 1
layers:
  - buttons:
      - - a
        - x
      - - x
        - x
      - - x
        - x
    knobs:
      - ccw: wheelup
        press: volumeup
        cw: wheeldown
